[app]
title = Master Earn
package.name = masterearn
package.domain = org.earn
source.dir = .
source.include_exts = py,png,jpg,kv,json
version = 1.0
requirements = python3,kivy==2.1.0,kivmob,android,pyjnius
orientation = portrait
android.permissions = INTERNET,ACCESS_NETWORK_STATE
android.api = 31
android.minapi = 21
android.archs = armeabi-v7a, arm64-v8a
